Реализовал оба класса
klimmerst/some_date-efimov pull request #1
Opened 2021-02-19 01:25 UTC by klimmerst

К тестам пока не приступал, но в ручном режиме потестил, вроде работает правильно. Не понял что делать с __add__ если мы прибавляем к дате 28.2.2003 таймдельту из (2, 10, 0): если складывать сначала дни, получится 2 января 2004, если месяцы, то 30.12.2003.

2021-02-19 01:28 UTC, klimmerst commented
Написал код изначально в ветке master, сделал из неё первый commit. Потом увидел, попробовал сделать revert, ну а потом сделал cherry-pick и только потом push. Не очень понял, правильно ли сделал и почему я отправлял последний commit, а видны все 3.

2021-02-19 01:48 UTC, klimmerst commented
<img width="367" alt="Снимок экрана 2021-02-19 в 3 42 57 AM" src="https://user-images.githubusercontent.com/18419291/108445362-4f28ae80-726d-11eb-98ec-b26f889a0158.png">

Не понимаю почему у меня сеттеры стали подсвечиваться белым часть названия. Они такие стали только в классе Date.

2021-02-20 18:54 UTC, klimmerst commented
Про подсвеченные сеттеры выше понял из лекции, спасибо.

2021-02-25 21:23 UTC, EnotYoyo requested changes
Тестов не хватает

2021-02-25 21:23 UTC, EnotYoyo commented on date.py
> +        if days is None:
Это можно в одну строчку: self.days = days or 0

2021-02-25 21:23 UTC, EnotYoyo commented on date.py
> +    __slots__ = ('_day', '_month', '_year')
круто :)

2021-02-25 21:23 UTC, EnotYoyo commented on date.py
> +            self._month = args[1]
можно так: self._day, self._month, self._year = args

2021-02-25 21:23 UTC, EnotYoyo commented on date.py
> +        return f'{self._day}.{self._month}.{self._year}'
А где пагинаторы? то есть строка должна дополняться нулями (01.01.0042)

2021-02-25 21:23 UTC, EnotYoyo commented on date.py
> +        return True if year % 4 == 0 and year % 100 != 0 or year % 400 == 0 else False
Можно просто return year % 4 == 0 and year % 100 != 0 or year % 400 == 0 :)

2021-02-25 21:23 UTC, EnotYoyo commented on date.py
> +            self._month = month
такс. А если у меня было 31 января, я поменял на февраль, получается 31 февраля будет?

2021-02-25 21:23 UTC, EnotYoyo commented on date.py
> +        new_instance = eval(repr(self))  # Date(self._day, self._month, self._year)
лучше все же Date(self.day, self.month, self.year). Eval - это довольно специфичная функция и редко используется в реальном коде

2021-02-25 21:23 UTC, EnotYoyo commented on date.py
> +            leap_year = self._year % 4 == 0 and self._year % 100 != 0 or self._year % 400 == 0
есть метод, можно его вызвать

2021-02-25 21:23 UTC, EnotYoyo commented on date.py
> +            if self._day < Date.DAY_OF_MONTH[leap_year][self._month - 1]:
есть метод получения максимального кол-ва дней в месяце

2021-02-26 19:20 UTC, klimmerst commented
Вроде, всё исправил. Тесты написал.

2021-03-03 19:19 UTC, EnotYoyo requested changes
А травис?)

2021-03-03 19:19 UTC, EnotYoyo commented on date.py
> +        leap_days = self._year // 4
так не каждый четвертый год является високосным (правило с сотнями)

2021-03-04 21:29 UTC, klimmerst commented on date.py
> +        leap_days = self._year // 4
пофиксил

2021-03-04 21:30 UTC, klimmerst commented
Сделал travis. Он фэйлился постоянно если было   - PYTHONPATH=. pytest --cov-report term-missing --cov date tests
Из логов было видно, будто тестов вообще нет, 0% покрытия. После того, как вынес файл с тестами из папки  и написал в .travis.yml это:  --cov date testing_date.py то проверки прошли.

2021-03-04 21:33 UTC, klimmerst commented
![image](https://user-images.githubusercontent.com/18419291/110033333-501c0e80-7d4a-11eb-952b-673dc7b5c5c3.png)

2021-03-05 17:55 UTC, EnotYoyo commented
> ![image](https://user-images.githubusercontent.com/18419291/110033333-501c0e80-7d4a-11eb-952b-673dc7b5c5c3.png)

У Вас файл с тестами неправильно называется. Он должен начинаться с test_,чтобы его pytest нашел

2021-03-05 17:58 UTC, EnotYoyo approved these changes
Засуньте тесты обратно в папочку и принято :)

2021-03-06 10:08 UTC, klimmerst commented
На всякий случай отправил re-request.

2021-03-06 10:33 UTC, EnotYoyo commented
Я его уже заапрувил :)

2021-03-06 20:28 UTC, merged